name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Loguearse en docker
      run: |
        echo "Logueandose..."
        docker login -e ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_TOKEN}}
   # - uses: actions/checkout@v4
   # - name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
